### ISSUE TITLE
What is an App Shell and why is it useful?

### ISSUE THREAD

**Issue by BryanCrotaz** [DockYard/ember-app-shell#2]
Add something to readme?

**Comment by bcardarella** [comment]
Confirm. In the mean time: https://developers.google.com/web/fundamentals/architecture/app-shell

**Comment by lolmaus** [comment]
+1.

I also tried to google it up and made a conclusion that an "app shell" is a frontend of a progressive web app.

What does it have to do with headless Chrome, though?

**Comment by ghost** [comment]
I have improved the readme, let me know if it's sufficient details to make you understand what it does.

**Comment by lolmaus** [comment]
It is, thank you. :bow:

**Comment by ghost** [comment]
Awesome!
