### ISSUE TITLE
Ember app not ready on load event

### ISSUE THREAD

**Issue by topaxi** [DockYard/ember-app-shell#6]
Currently ember-app-shell only waits for the load event [here](https://github.com/DockYard/ember-app-shell/blob/master/index.js#L49).

This does not seem to work in one of my applications: [github:opensource-challenge.ch](https://github.com/opensource-challenge/opensource-challenge-client)

If I delay the `document.body.querySelector('.ember-view').outerHTML` call by some milliseconds it works again. Do we have a way to wait for the ember route to be rendered?

**Comment by ghost** [comment]
Adding a config variable to wait a while might be an idea.

**Comment by ghost** [comment]
You also have full access to the dev console. So if you can run a command in the console that can test for it, you could use that.

(I'm using the you form, because I'm really busy the coming two workweeks, so I'm not sure if I can get to it.)

**Comment by bcardarella** [comment]
I think there needs to be some additional logic to guarantee that the app has loaded completely. Relying on `Page.loadEventFired` only guarantees that the page has loaded, not that the Ember app has completed rendering.

I'll make a PR with a suggested change that should guarantee that the Ember app has completed its render cycle before app-shell attempts to parse the HTML
